### ISSUE TITLE
AllocOps and load/store ops in Launch and Segment

### ISSUE THREAD

**Issue by hunhoffe** [Xilinx/mlir-air#662]
As part of the channel examples, and an interesting discussion on allocation, I wanted to see if I could explicitly allocate L3 memory in a launch and L2 memory in a segment. To this end, I wrote the `programming_examples/channel_examples/hierarchical_alloc` example in this PR: https://github.com/Xilinx/mlir-air/pull/661

Currently, it fails to fully compile with an error like this:
```
Traceback (most recent call last):
  File "mlir-air/programming_examples/channel_examples/hierarchical_alloc/run.py", line 86, in <module>
    test_main(build_module, verbose=args.verbose)
  File "mlir-air/programming_examples/channel_examples/hierarchical_alloc/run.py", line 45, in test_main
    addone = backend.compile_and_load(mlir_module)
  File "mlir-air/install-xrt/python/air/backend/xrt.py", line 222, in compile_and_load
    c = self.compile(module)
  File "mlir-air/install-xrt/python/air/backend/xrt.py", line 117, in compile
    aircc.run(air_module, aircc_options)
  File "mlir-air/install-xrt/python/air/compiler/aircc/main.py", line 449, in run
    run_passes(air_to_npu_passes, air_to_npu_module, opts, air_to_npu_file)
  File "mlir-air/install-xrt/python/air/compiler/aircc/main.py", line 113, in run_passes
    PassManager.parse(pass_pipeline).run(mlir_module.operation)
air._mlir_libs._site_initialize.<locals>.MLIRError: Failure while executing pass pipeline:
error: "-":145:20: failed to legalize operation 'airrt.alloc' marked as erased
 note: "-":145:20: see current operation: %16 = "airrt.alloc"() : () -> memref<1x4xi32, 1 : i32>
 note: "-":161:16: found live user of result #0: %5 = memref.load %2[%c0, %c0] : memref<1x4xi32, 1 : i32>
make: *** [Makefile:9: run] Error 1
```

I'm not fully confident this example is a reasonable thing to ask the air compiler to handle, but I think it might be. If it is not, let me know, and I will either change or erase the example!

**Comment by hunhoffe** [comment]
Closing because discussed in offline discussion. loads/stores aren't possible in launch/segment
